export const SEARCHING = 'SEARCHING';
export const SEARCHING_SUCCESS = 'SEARCHING_SUCCESS';
export const SEARCHING_ERROR = 'SEARCHING_ERROR';
export const SEARCHING_STARTED = 'SEARCHING_STARTED';

export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';

export const LOGGING_IN = 'LOGGING_IN';
export const LOGGING_IN_SUCCESS = 'LOGGING_IN_SUCCESS';
export const LOGGING_IN_ERROR = 'LOGGING_IN_ERROR';
export const LOGGING_IN_STARTED = 'LOGGING_IN_STARTED';

export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const REGISTRATION_STARTED = 'REGISTRATION_STARTED';

export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_ERROR = 'LOAD_PROFILE_ERROR';
export const LOAD_PROFILE_STARTED = 'LOAD_PROFILE_STARTED';

export const LOCATION_REQUEST_SUCCESS = 'LOCATION_REQUEST_SUCCESS';
export const LOCATION_REQUEST_ERROR = 'LOCATION_REQUEST_ERROR';
export const LOCATION_REQUEST_STARTED = 'LOCATION_REQUEST_STARTED';
