export const SEARCHING = 'SEARCHING';
export const SEARCHING_SUCCESS = 'SEARCHING_SUCCESS';
export const SEARCHING_ERROR = 'SEARCHING_ERROR';
export const SEARCHING_STARTED = 'SEARCHING_STARTED';

export const LOGGING_IN = 'LOGGING_IN';
export const LOGGING_IN_SUCCESS = 'LOGGING_IN_SUCCESS';
export const LOGGING_IN_ERROR = 'LOGGING_IN_ERROR';
export const LOGGING_IN_STARTED = 'LOGGING_IN_STARTED';
